version: "3.9"

services:
  qdrant:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: qdrant-local

    ports:
      - "6333:6333"   # REST + Dashboard UI
      - "6334:6334"   # gRPC

    volumes:
      - ./qdrant_data:/qdrant/storage

    environment:
      QDRANT__SERVICE__HTTP_PORT: 6333
      QDRANT__SERVICE__GRPC_PORT: 6334

    restart: unless-stopped
